; PlatformIO Project Configuration File

[platformio]
default_envs = giga_r1_m7_robot


[env]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/pololu/motoron-arduino.git
    https://github.com/kkloesener/MFRC522_I2C.git
    https://github.com/pololu/qtr-sensors-arduino.git
build_unflags =
    -std=c++11
    -std=gnu++11
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -D LOG_LEVEL=LOG_LEVEL_DEBUG
    -D LOG_BAUDRATE=115200

[env:giga_r1_m7]
build_flags =
    ${env.build_flags}
    -D APP_MODE=0
extra_scripts = pre:scripts/disable_serial_upload_touch.py

[env:giga_r1_m7_auto_upload]
build_flags =
    ${env.build_flags}
    -D APP_MODE=3
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_robot]
build_flags =
    ${env.build_flags}
    -D APP_MODE=0
build_src_filter =
    +<main.cpp>
    +<robot_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_wifi_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=1
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_motor_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=2
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_upload_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=3
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_encoder_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=4
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_qtr_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=5
build_src_filter =
    +<main.cpp>
    +<qtr_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_button_led_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=6
lib_deps =
build_src_filter =
    +<main.cpp>
    +<button_led_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_simple_motoron_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=7
build_src_filter =
    +<main.cpp>
    +<simple_motoron_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_ultrasonic_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=8
lib_deps =
build_src_filter =
    +<main.cpp>
    +<ultrasonic_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_servo_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=9
lib_deps =
build_src_filter =
    +<main.cpp>
    +<servo_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_rfid_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=10
build_src_filter =
    +<main.cpp>
    +<rfid_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_ir_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=11
monitor_speed = 9600
build_src_filter =
    +<main.cpp>
    +<ir_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_qtr_lib_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=12
build_src_filter =
    +<main.cpp>
    +<qtr_lib_test_app.cpp>
extra_scripts = pre:scripts/giga_auto_dfu_upload.py
