; PlatformIO Project Configuration File

[platformio]
default_envs = giga_r1_m7_motor_test


[env]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
build_unflags =
    -std=c++11
    -std=gnu++11
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -D LOG_LEVEL=LOG_LEVEL_DEBUG
    -D LOG_BAUDRATE=115200

[env:giga_r1_m7]
build_flags =
    ${env.build_flags}
    -D APP_MODE=0
extra_scripts = pre:scripts/disable_serial_upload_touch.py

[env:giga_r1_m7_auto_upload]
build_flags =
    ${env.build_flags}
    -D APP_MODE=0
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_robot]
build_flags =
    ${env.build_flags}
    -D APP_MODE=0
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_wifi_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=1
extra_scripts = pre:scripts/giga_auto_dfu_upload.py

[env:giga_r1_m7_motor_test]
build_flags =
    ${env.build_flags}
    -D APP_MODE=2
extra_scripts = pre:scripts/giga_auto_dfu_upload.py
