#include <Arduino.h>

#include "../Programming_Viva/ArenaTypes.h"

// Prototypes needed before including Programming_Viva/Main.ino as C++.
void beginMotoron();
void beginIMU();
void readLeftEncoder();
void readRightEncoder();
void setupRFID();
void setupServos();
void setup_tunnel();
void setupMessages();
void reset_calibration();
void serviceServoPulses();
void update_turn_angle();
void messagesLoop();
void RunTest3();
void startTunnelEntry();
bool arenaGoToExit();
bool arenaReturnToEntrance();
void read_rc_discharge_times();
void stopMotors();
void Blue();
void update_calibration();
void print_calibration();
void Yellow();
void Green();
void calibrate_gyro_z_bias();
bool messagesRobotAllowedToMove();
void Red();
void Flash(int previousStateRed);
void setMotors(int16_t leftSpeed, int16_t rightSpeed);
void run_tunnel_step();

// Main.ino owns all Programming_Viva globals. Rename its Arduino entry points
// so PlatformIO still enters through src/main.cpp -> robot_app_setup/loop.
#define setup programming_viva_setup
#define loop programming_viva_loop
#include "../Programming_Viva/Main.ino"
#undef setup
#undef loop

// Cross-module prototypes normally generated by the Arduino .ino builder.
bool imu_write_register(TwoWire& bus, uint8_t address, uint8_t reg, uint8_t value);
bool imu_read_registers(TwoWire& bus, uint8_t address, uint8_t start_reg, uint8_t* buffer, uint8_t length);
bool imu_read_u8(TwoWire& bus, uint8_t address, uint8_t reg, uint8_t& value);
bool imu_probe_address(TwoWire& bus, uint8_t address);
void imu_print_hex_byte(uint8_t value);
uint8_t imu_count_expected_devices(TwoWire& bus);
void select_best_imu_i2c_bus();
bool setup_adxl345();
bool setup_itg320x();
bool setup_hmc5883l();
bool setup_bmp280();
bool read_itg320x(Axis3& gyro, float& temperature_c);
float gyro_z_to_dps(int16_t raw_z);
float corrected_gyro_z_dps(int16_t raw_z);
void reset_turn_angle();

void read_rc_discharge_times();
void update_calibrated_values();
uint16_t target_value_at(uint8_t sensor_index);
uint16_t line_peak();
bool update_line_found();
void update_last_line_side();
bool blackLineDetectedDuringTurn();
bool intersection_detected();
bool sensor_active(uint8_t index);
uint8_t count_active_range(uint8_t start_index, uint8_t end_index);
JunctionType detect_junction_type();
const char* junctionTypeName(JunctionType type);
int32_t estimate_line_position();
void set_follow_state(FollowState next_state);
void update_line_following();

long getLeftEncoder();
long getRightEncoder();
void printEncoders();
void configureMotor(uint8_t motor);
void drive_forward();
void follow_line(int32_t error);
void recover_lost_line();
void centreAfterRFID();
void centreAfterIR();
void drive_forward_gap();

bool turnUntilLineOrAngle(float max_degrees, int8_t direction, float ignore_line_until_deg);
bool turnLeft90WithLines();
bool turnRight90WithLines();
bool turnLeft180WithLines();
bool turnRight180WithLines();
void turnLeft90();
void turnRight90();
void turnLeft180();
void turnRight180();

const char* state_name();
void print_array(const char* label, const uint16_t* values);
void print_line_status();

bool rfid_firmware_version_valid(byte version);
void print_hex2(byte value);
void init_reader_without_soft_reset();
bool i2c_device_present(uint8_t address);
bool handleRFID();

int angleToPulseUs(int angle);
void waitWithServo(unsigned long ms);
void writeUpperServo(int angle);
void writeLowerServo(int angle);
void closeBothGates();
void dispenseOne();

void plant();
bool checkStopInputsDuringTest();
bool scanRFIDForTest();
bool driveUntilRFIDAndPlant(uint8_t target_scans);

void handleIncomingMessage(const char* from_board_id, const uint8_t* payload, size_t length);
bool messagesConnected();
bool messagesRemoteEnabled();
bool messagesEmergencyActive();
bool messagesDisableActive();
bool messagesHaveMap();
bool messagesCopyLastMap(uint8_t* out_map21, size_t out_size);
bool messagesGetLastFertilityReply(const char* tag_id, int8_t* x, int8_t* y, uint8_t* state);
bool messagesWaitForFertilityReply(const char* tag_id, unsigned long timeout_ms, int8_t* x, int8_t* y, uint8_t* state);
bool messagesSendToBoard(const char* target_board_id, const char* text);
bool messagesSendToBoard(const char* target_board_id, const uint8_t* data, size_t length);
bool messagesSendToBoard(uint8_t target_board_id, const char* text);
bool messagesSendToBoard(uint8_t target_board_id, const uint8_t* data, size_t length);
bool messagesSendToGroup(const char* text);
bool messagesSendToGroup(const uint8_t* data, size_t length);
bool messagesSendRegister();
bool messagesBroadcastHeartbeat();
bool messagesSendIsFertile(const char* tag_id);
bool messagesSendSeedPlanted(const char* tag_id);
bool messagesSendOpenAirlock(char airlock, const char* tag_id);
bool messagesSendReviveRequest(const char* target_team, const char* target_board);
bool messagesSendGetMap();

float read_ultrasonic_mm(uint8_t trig_pin, uint8_t echo_pin);
float side_distance_mm();
float forward_distance_mm();
void wall_follow_step();
void drive_into_tunnel();
void set_tunnel_state(TunnelState next);

bool arenaInside(int8_t x, int8_t y);
bool arenaIsDoorway(int8_t x, int8_t y);
bool arenaIsWallCell(int8_t x, int8_t y);
void arenaClearMapToUnknown();
uint8_t arenaReadTwoBitCell(const uint8_t* map21, uint16_t cell_index);
void arenaDecodeGetMap21(const uint8_t* map21);
void arenaRequestAndRefreshMap();
void arenaExpireTemporaryObstacles();
bool arenaBlocked(int8_t x, int8_t y);
unsigned long arenaTemporaryObstacleDuration(ArenaPoint p);
bool arenaCellExplored(int8_t x, int8_t y);
uint16_t arenaTravelCost(ArenaPoint from, ArenaPoint to, ArenaPoint parent);
ArenaPoint arenaNextPoint(ArenaPoint p, ArenaHeading h);
void arenaMarkTemporaryObstacle(ArenaPoint p);
bool arenaObstacleAhead();
void uidToText(char* out, size_t out_size);
bool arenaLookupRFID(const char* uid, ArenaPoint* out);
bool arenaUpdatePoseFromRFID();
ArenaHeading arenaHeadingForStep(ArenaPoint from, ArenaPoint to);
int8_t arenaHeadingDiff(ArenaHeading from, ArenaHeading to);
bool arenaTurnTo(ArenaHeading target);
bool arenaFindPath(ArenaPoint start, ArenaPoint goal, ArenaPoint* path, uint8_t* path_len);
bool arenaDriveOneCellTo(ArenaPoint next);
bool arenaPathfindTo(ArenaPoint goal);

#include "../Programming_Viva/LEDs.ino"
#include "../Programming_Viva/Servos.ino"
#include "../Programming_Viva/MotorEncoders.ino"
#include "../Programming_Viva/IMU.ino"
#include "../Programming_Viva/LineSensors.ino"
#include "../Programming_Viva/Turning.ino"
#include "../Programming_Viva/Printing.ino"
#include "../Programming_Viva/RFID.ino"
#include "../Programming_Viva/Messages.ino"
#include "../Programming_Viva/Tunnel_Entry.ino"
#include "../Programming_Viva/ArenaPathfinding.ino"
#include "../Programming_Viva/RobotBehaviour.ino"

namespace {

enum class EasyState {
  Calibrating,
  BaseLineToAirlockB,
  Tunnel,
  ArenaPlanting,
  Complete,
  Stopped,
};

constexpr unsigned long EASY_STATUS_INTERVAL_MS = 1000;
constexpr unsigned long EASY_FERTILITY_REPLY_TIMEOUT_MS = 1500;

EasyState easy_state = EasyState::Calibrating;
EasyState easy_resume_state = EasyState::BaseLineToAirlockB;
unsigned long easy_last_status_ms = 0;
unsigned long easy_line_status_ms = 0;
bool easy_started = false;
bool easy_airlock_requested = false;
bool easy_tunnel_started = false;
uint8_t easy_planted_count = 0;

const char* easyStateName(EasyState state)
{
  switch (state) {
    case EasyState::Calibrating: return "calibrating";
    case EasyState::BaseLineToAirlockB: return "base_line_to_airlock_b";
    case EasyState::Tunnel: return "tunnel";
    case EasyState::ArenaPlanting: return "arena_planting";
    case EasyState::Complete: return "complete";
    case EasyState::Stopped: return "stopped";
  }

  return "unknown";
}

void printEasyStatus()
{
  const unsigned long now_ms = millis();
  if (now_ms - easy_last_status_ms < EASY_STATUS_INTERVAL_MS) {
    return;
  }

  easy_last_status_ms = now_ms;
  Serial.print("easy_state=");
  Serial.print(easyStateName(easy_state));
  Serial.print(" mission_phase=");
  Serial.print(static_cast<int>(mission_phase));
  Serial.print(" seeds_left=");
  Serial.print(seeds);
  Serial.print(" planted=");
  Serial.print(easy_planted_count);
  Serial.print(" mqtt=");
  Serial.println(messagesConnected() ? 1 : 0);
}

void processEasySerial()
{
  while (Serial.available() > 0) {
    const char command = static_cast<char>(Serial.read());

    if (command == '0' || command == 'x' || command == 'X') {
      running = !running;
      if (!running) {
        if (easy_state != EasyState::Stopped) {
          easy_resume_state = easy_state;
        }
        stopMotors();
        easy_state = EasyState::Stopped;
        Serial.println("easy_stop=serial");
      } else {
        easy_state = easy_resume_state;
        Serial.println("easy_resume=serial");
      }
    } else if (command == 'r' || command == 'R') {
      easy_state = EasyState::BaseLineToAirlockB;
      easy_airlock_requested = false;
      easy_tunnel_started = false;
      mission_phase = MissionPhase::BaseToGate;
      running = true;
      run_enabled = true;
      Serial.println("easy_restart=serial");
    } else if (command == 'd' || command == 'D') {
      if (seeds > 0) {
        dispenseOne();
        --seeds;
        ++easy_planted_count;
        Serial.println("easy_manual_dispense=1");
      }
    }
  }
}

void updateEasyButtons()
{
  const int off_button_pressed = digitalRead(OffButtonPin);
  const int revive_button_pressed = digitalRead(RevButtonPin);

  Reviving = false;

  if (off_button_pressed == LOW && previousOffButtonPressed != LOW) {
    running = !running;
    delay(50);

    if (!running) {
      if (easy_state != EasyState::Stopped) {
        easy_resume_state = easy_state;
      }
      easy_state = EasyState::Stopped;
      stopMotors();
      Serial.println("easy_stop=button");
    } else {
      easy_state = easy_resume_state;
      Serial.println("easy_resume=button");
    }
  } else if (revive_button_pressed == LOW) {
    Reviving = true;
    delay(50);
  }

  previousOffButtonPressed = off_button_pressed;
}

bool readRFIDUid(char* uid, size_t uid_size)
{
  if (!(rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial())) {
    return false;
  }

  if (millis() - lastScanTime < RFID_SCAN_COOLDOWN_MS) {
    rfid.PICC_HaltA();
    return false;
  }

  uidToText(uid, uid_size);
  lastScanTime = millis();
  rfid.PICC_HaltA();
  return uid[0] != '\0';
}

bool easyRequestAirlockFromBaseLine()
{
  char uid[32];
  if (!readRFIDUid(uid, sizeof(uid))) {
    return false;
  }

  stopMotors();
  Serial.print("easy_base_airlock_tag=");
  Serial.println(uid);

  if (messagesConnected()) {
    const bool ok = messagesSendOpenAirlock('B', uid);
    Serial.print("easy_open_airlock_b_sent=");
    Serial.println(ok ? 1 : 0);
  } else {
    Serial.println("easy_warning=no_mqtt_for_airlock_b");
  }

  easy_airlock_requested = true;
  return true;
}

bool easyHandleArenaRFID()
{
  char uid[32];
  if (!readRFIDUid(uid, sizeof(uid))) {
    return false;
  }

  stopMotors();
  Serial.print("easy_arena_tag=");
  Serial.println(uid);

  bool fertile = false;
  int8_t tag_x = -1;
  int8_t tag_y = -1;
  uint8_t state = 0;

  if (messagesConnected() && messagesSendIsFertile(uid)) {
    if (messagesWaitForFertilityReply(
          uid,
          EASY_FERTILITY_REPLY_TIMEOUT_MS,
          &tag_x,
          &tag_y,
          &state)) {
      fertile = state == 2;
      Serial.print("easy_fertility_reply x=");
      Serial.print(tag_x);
      Serial.print(" y=");
      Serial.print(tag_y);
      Serial.print(" state=");
      Serial.println(state);
    } else {
      Serial.println("easy_warning=fertility_no_reply");
    }
  } else {
    Serial.println("easy_warning=fertility_request_not_sent");
  }

  if (fertile && seeds > 0) {
    centreAfterRFID();
    dispenseOne();
    --seeds;
    ++easy_planted_count;
    messagesSendSeedPlanted(uid);

    Serial.print("easy_seed_planted uid=");
    Serial.print(uid);
    Serial.print(" seeds_left=");
    Serial.println(seeds);

    if (seeds <= 0) {
      easy_state = EasyState::Complete;
      stopMotors();
      Green();
    }

    return true;
  }

  Serial.print("easy_no_plant fertile=");
  Serial.print(fertile ? 1 : 0);
  Serial.print(" seeds_left=");
  Serial.println(seeds);
  return false;
}

void runEasyLineFollowingStep()
{
  if (millis() - last_control_ms < CONTROL_INTERVAL_MS) {
    return;
  }

  last_control_ms = millis();
  read_rc_discharge_times();
  update_line_following();
}

void runEasyBaseLineStep()
{
  if (easyRequestAirlockFromBaseLine()) {
    easy_state = EasyState::Tunnel;
    return;
  }

  runEasyLineFollowingStep();
}

void runEasyTunnelStep()
{
  if (!easy_tunnel_started) {
    startTunnelEntry();
    easy_tunnel_started = true;
  }

  if (mission_phase == MissionPhase::Tunnel &&
      millis() - last_control_ms >= CONTROL_INTERVAL_MS) {
    last_control_ms = millis();
    run_tunnel_step();
  }

  if (mission_phase == MissionPhase::Arena) {
    easy_state = EasyState::ArenaPlanting;
    stopMotors();
    Serial.println("easy_phase=arena_planting");
  }
}

void runEasyArenaPlantingStep()
{
  if (seeds <= 0) {
    easy_state = EasyState::Complete;
    stopMotors();
    Green();
    return;
  }

  if (easyHandleArenaRFID()) {
    return;
  }

  runEasyLineFollowingStep();

  if (millis() - easy_line_status_ms >= LINE_STATUS_INTERVAL_MS) {
    easy_line_status_ms = millis();
    print_line_status();
  }
}

void runEasyReadyLoop()
{
  processEasySerial();
  updateEasyButtons();
  read_rc_discharge_times();

  if (!messagesRobotAllowedToMove()) {
    run_enabled = false;
    if (easy_state != EasyState::Stopped) {
      easy_resume_state = easy_state;
    }
    easy_state = EasyState::Stopped;
    stopMotors();
    Red();
    delay(25);
    return;
  }

  if (!running || easy_state == EasyState::Stopped) {
    run_enabled = false;
    Flash(previousStateRed);
    ++previousStateRed;
    stopMotors();
    delay(25);
    return;
  }

  run_enabled = true;

  if (Reviving) {
    Green();
    stopMotors();
    delay(500);
    setMotors(-BASE_SPEED, -BASE_SPEED);
    return;
  }

  if (!easy_started) {
    easy_started = true;
    easy_state = EasyState::BaseLineToAirlockB;
    last_control_ms = millis();
    Serial.println("easy_start=auto_base_line_to_airlock_b");
  }

  Red();

  switch (easy_state) {
    case EasyState::Calibrating:
      easy_state = EasyState::BaseLineToAirlockB;
      break;
    case EasyState::BaseLineToAirlockB:
      runEasyBaseLineStep();
      break;
    case EasyState::Tunnel:
      runEasyTunnelStep();
      break;
    case EasyState::ArenaPlanting:
      runEasyArenaPlantingStep();
      break;
    case EasyState::Complete:
      stopMotors();
      Green();
      break;
    case EasyState::Stopped:
      stopMotors();
      break;
  }
}

}  // namespace

void robot_app_setup()
{
  programming_viva_setup();
  Serial.println("=== Easy difficulty autonomous app ===");
  Serial.println("Flow: calibrate -> line to B tag -> tunnel -> arena fertile planting.");
  Serial.println("Serial: 0/x stop-toggle, r restart Easy flow, d manual dispense.");
}

void robot_app_loop()
{
  serviceServoPulses();
  update_turn_angle();
  messagesLoop();
  printEasyStatus();

  if (startup_cal_state != StartupCalState::Ready) {
    easy_state = EasyState::Calibrating;
    programming_viva_loop();
    return;
  }

  runEasyReadyLoop();
}
